[package]
name = "fogo_program"
version = "0.1.0"
edition = "2021"

[lib]
name = "fogo_program"
crate type = ["cdylib", "lib"]

[dependencies]
solana_program = "1.18.26"

[features]
no entrypoint = []
